### ISSUE TITLE
Feeding the netcdf location to conda-build on macOS

### ISSUE THREAD

**Issue by Zeitsperre** [conda-forge/netcdf-cxx-legacy-feedstock#7]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'm trying to build something on conda-forge for macOS that requires the NetCDF4-C headers (https://github.com/conda-forge/raven-hydro-feedstock/pull/2). Using `homebrew` the necessary headers are installed and linked with `brew install netcdf`, but it appears to be more complicated for macOS with conda-forge (everything works well for Linux).

The errors I see tell me that `netcdf` is just not found for some reason:
```
In file included from Interflow.cpp:8:
In file included from ./HydroProcessABC.h:9:
./RavenInclude.h:22:10: fatal error: 'netcdf.h' file not found
#include <netcdf.h>
         ^~~~~~~~~~
1 error generated.
In file included from OverlapExchangeClass.cpp:5:
In file included from ./Properties.h:24:
./RavenInclude.h:22:10: fatal error: 'netcdf.h' file not found
#include <netcdf.h>
         ^~~~~~~~~~
```

I have tried dynamically linking to them using `LDLIBS   := $(shell nc-config --libs)` in my Makefile, but that doesn't seem to have any effect (and it's difficult to determine whether it's even working). Ultimately, **I'm wondering where I can find the <netcdf.h> file in a fresh conda-forge on macOS installation, and how I can feed this information to the necessary flags when building my packages**.

Thanks for the help!

(Ping @julemai)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by xylar** [comment]
@Zeitsperre, I've had a look and I don't think your code (`raven-hydro`) depends on either C++ version (current or legacy) of NetCDF.  You just need the C version (`libnetcdf`) as far as I can tell.  The header `netcdf.h` comes from that package.  The problem with the OSX build of your package presumably has something to do with the build not looking for the include files in the right place on OSX.  I'll try to help but I don't think it's anything to do with this feedstock and you can probably remove the `netcdf-cxx-legacy` dependency entirely.  It certainly wasn't needed in a linux test build I did of your code (and it seems like you didn't need it before the current PR).

**Comment by Zeitsperre** [comment]
Thanks again for all this help! You went above and beyond in helping me in understanding where I was going wrong. I greatly appreciate it!

**Comment by xylar** [comment]
No problem, glad to help.  Ping me if you run into trouble on conda-forge in the future.
